//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Repository
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SoftoxEntities : DbContext
    {
        public SoftoxEntities()
            : base("name=SoftoxEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<T_Category> T_Category { get; set; }
        public DbSet<T_Comment> T_Comment { get; set; }
        public DbSet<T_Top> T_Top { get; set; }
        public DbSet<T_TopElement> T_TopElement { get; set; }
        public DbSet<T_User> T_User { get; set; }
    }
}
