//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Category
    {
        public T_Category()
        {
            this.T_Top = new HashSet<T_Top>();
        }
    
        public int cat_id { get; set; }
        public string cat_name { get; set; }
    
        public virtual ICollection<T_Top> T_Top { get; set; }
    }
}
