//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Comment
    {
        public int com_id { get; set; }
        public int com_fk_top_id { get; set; }
        public int com_fk_user_id { get; set; }
        public string com_text { get; set; }
        public System.DateTime com_date_entry { get; set; }
    
        public virtual T_Top T_Top { get; set; }
        public virtual T_User T_User { get; set; }
    }
}
