//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Top
    {
        public T_Top()
        {
            this.T_Comment = new HashSet<T_Comment>();
            this.T_TopElement = new HashSet<T_TopElement>();
        }
    
        public int top_id { get; set; }
        public int top_fk_cat_id { get; set; }
        public int top_fk_user_id { get; set; }
        public string top_title { get; set; }
        public string top_description { get; set; }
        public string top_source { get; set; }
        public System.DateTime top_date_creation { get; set; }
        public Nullable<System.DateTime> top_date_modification { get; set; }
        public int top_view_count { get; set; }
        public byte top_status { get; set; }
    
        public virtual T_Category T_Category { get; set; }
        public virtual ICollection<T_Comment> T_Comment { get; set; }
        public virtual T_User T_User { get; set; }
        public virtual ICollection<T_TopElement> T_TopElement { get; set; }
    }
}
