//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_TopElement
    {
        public int topel_id { get; set; }
        public int topel_fk_top_id { get; set; }
        public int topel_number { get; set; }
        public string topel_name { get; set; }
        public string topel_desc { get; set; }
    
        public virtual T_Top T_Top { get; set; }
    }
}
