//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_User
    {
        public T_User()
        {
            this.T_Comment = new HashSet<T_Comment>();
            this.T_Top = new HashSet<T_Top>();
        }
    
        public int user_id { get; set; }
        public string user_name { get; set; }
        public string user_password { get; set; }
        public string user_desc { get; set; }
        public System.DateTime user_date_subscription { get; set; }
        public byte user_status { get; set; }
    
        public virtual ICollection<T_Comment> T_Comment { get; set; }
        public virtual ICollection<T_Top> T_Top { get; set; }
    }
}
